=== adalmauvil1-commits/Risk2x2Xml/xml/jugadas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="jugadas" type="jugadasType"/>
  <xs:complexType name="jugadasType">
    <xs:sequence>
      <xs:element type="ataqueType" name="ataque" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ataqueType">
    <xs:sequence>
      <xs:element type="tipoAtacaDefiende" name="ataca"/>
      <xs:element type="tipoAtacaDefiende" name="defiende"/>
      <xs:element type="tiradaType" name="tirada"/>
      <xs:element type="territorioType" name="territorio" maxOccurs="2" minOccurs="2"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tipoAtacaDefiende">
    <xs:sequence>
      <xs:element type="xs:positiveInteger" name="jugador"/>
      <xs:element type="xs:string" name="territorio"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tiradaType">
    <xs:sequence>
      <xs:element type="dadosType" name="dados" maxOccurs="2" minOccurs="2"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="dadosType">
    <xs:sequence>
      <xs:element type="tipoValorDado6" name="valor" maxOccurs="3" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="tipoValorDado6">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="6"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="territorioType">
    <xs:sequence>
      <xs:element type="xs:string" name="nombre"/>
      <xs:element type="xs:positiveInteger" name="propietario"/>
      <xs:element type="tipoMayorIgual0" name="ejercitos"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="tipoMayorIgual0">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="0"></xs:minInclusive>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== adalmauvil1-commits/Risk2x2Xml/doc/xml/jugadas0.xml
<jugadas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="jugadas.xsd">
    <ataque>
        <ataca>
            <jugador>1</jugador>
            <territorio>Buztintxuri</territorio>
        </ataca>
        <defiende>
            <jugador>2</jugador>
            <territorio>Arrosadia</territorio>
        </defiende>
        <tirada>
            <dados>
                <valor>4</valor>
                <valor>3</valor>
                <valor>2</valor>
            </dados>
            <dados>
                <valor>2</valor>
                <valor>1</valor>
            </dados>
        </tirada>
        <territorio>
            <nombre>Buztintxuri</nombre>
            <propietario>1</propietario>
            <ejercitos>4</ejercitos>
        </territorio>
        <territorio>
            <nombre>Arrosadia</nombre>
            <propietario>2</propietario>
            <ejercitos>1</ejercitos>
        </territorio>
    </ataque>
</jugadas>
