=== adalmauvil1-commits/Risk2x2Xml/xml/partida.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="partida" type="partidaType"/>
  <xs:complexType name="partidaType">
    <xs:sequence>
      <xs:element type="jugadoresType" name="jugadores"/>
      <xs:element type="mapaType" name="mapa"/>
      <xs:element type="jugadasType" name="jugadas"/>
    </xs:sequence>
    <xs:attribute type="xs:date" name="fecha"/>
    <xs:attribute type="xs:time" name="horaIni"/>
    <xs:attribute type="xs:time" name="horaFin"/>
  </xs:complexType>
  <xs:complexType name="jugadoresType">
    <xs:sequence>
      <xs:element type="jugadorType" name="jugador" maxOccurs="2" minOccurs="2"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="jugadorType">
    <xs:simpleContent>
      <xs:extension base="tipoNombre">
        <xs:attribute type="xs:positiveInteger" name="id" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="tipoNombre">
    <xs:restriction base="xs:string">
      <xs:maxLength value="12"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="mapaType">
    <xs:sequence>
      <xs:element type="territorioType" name="territorio" maxOccurs="4" minOccurs="4"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="territorioType">
    <xs:sequence>
      <xs:element type="xs:string" name="nombre"/>
      <xs:element type="xs:positiveInteger" name="propietario"/>
      <xs:element type="tipoMayorIgual0" name="ejercitos"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="tipoMayorIgual0">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="0"></xs:minInclusive>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="jugadasType">
    <xs:sequence>
      <xs:element type="ataqueType" name="ataque" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ataqueType">
    <xs:sequence>
      <xs:element type="tipoAtacaDefiende" name="ataca"/>
      <xs:element type="tipoAtacaDefiende" name="defiende"/>
      <xs:element type="tiradaType" name="tirada"/>
      <xs:element type="territorioType" name="territorio" maxOccurs="2" minOccurs="2"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tipoAtacaDefiende">
    <xs:sequence>
      <xs:element type="xs:positiveInteger" name="jugador"/>
      <xs:element type="xs:string" name="territorio"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tiradaType">
    <xs:sequence>
      <xs:element type="dadosType" name="dados" maxOccurs="2" minOccurs="2"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="dadosType">
    <xs:sequence>
      <xs:element type="tipoValorDado6" name="valor" maxOccurs="3" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="tipoValorDado6">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="6"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== adalmauvil1-commits/Risk2x2Xml/doc/xml/partida0.xml
<?xml version='1.0' encoding='UTF-8' ?>
<partida xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
         xsi:noNamespaceSchemaLocation='partida.xsd'
         fecha='2025-09-24'
         horaIni='23:20:45.516338'
         horaFin='23:23:30.540328'>
    <jugadores>
        <jugador id='1'>Mikel</jugador>
        <jugador id='2'>Laura</jugador>
    </jugadores>
    <mapa>
        <territorio>
            <nombre>Buztintxuri</nombre>
            <propietario>1</propietario>
            <ejercitos>4</ejercitos>
        </territorio>
        <territorio>
            <nombre>Arrosadia</nombre>
            <propietario>2</propietario>
            <ejercitos>3</ejercitos>
        </territorio>
        <territorio>
            <nombre>Txantrea</nombre>
            <propietario>1</propietario>
            <ejercitos>3</ejercitos>
        </territorio>
        <territorio>
            <nombre>Iturrama</nombre>
            <propietario>2</propietario>
            <ejercitos>4</ejercitos>
        </territorio>
    </mapa>
    <jugadas>
        <ataque>
            <ataca>
                <jugador>1</jugador>
                <territorio>Buztintxuri</territorio>
            </ataca>
            <defiende>
                <jugador>2</jugador>
                <territorio>Arrosadia</territorio>
            </defiende>
            <tirada>
                <dados>
                    <valor>5</valor>
                    <valor>3</valor>
                    <valor>2</valor>
                </dados>
                <dados>
                    <valor>4</valor>
                    <valor>2</valor>
                </dados>
            </tirada>
            <territorio>
                <nombre>Buztintxuri</nombre>
                <propietario>1</propietario>
                <ejercitos>4</ejercitos>
            </territorio>
            <territorio>
                <nombre>Arrosadia</nombre>
                <propietario>2</propietario>
                <ejercitos>1</ejercitos>
            </territorio>
        </ataque>
    </jugadas>
</partida>
