=== adalmauvil1-commits/Risk2x2Xml/xml/tirada.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="tirada" type="tiradaType"/>
  <xs:complexType name="tiradaType">
    <xs:sequence>
      <xs:element type="dadosType" name="dados" maxOccurs="2" minOccurs="2"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="dadosType">
    <xs:sequence>
      <xs:element type="tipoValorDado6" name="valor" maxOccurs="3" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="tipoValorDado6">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="6"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== adalmauvil1-commits/Risk2x2Xml/doc/xml/tirada0.xml
<tirada xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="tirada.xsd">
    <dados>
        <valor>4</valor>
        <valor>4</valor>
        <valor>2</valor>
    </dados>
    <dados>
        <valor>6</valor>
        <valor>6</valor>
    </dados>
</tirada>
