=== adalmauvil1-commits/Risk2x2Xml/doc/xml/mapa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mapa" type="mapaType"/>
  <xs:complexType name="mapaType">
    <xs:sequence>
      <xs:element type="territorioType" name="territorio" maxOccurs="4" minOccurs="4"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="territorioType">
    <xs:sequence>
      <xs:element type="xs:string" name="nombre"/>
      <xs:element type="xs:positiveInteger" name="propietario"/>
      <xs:element type="tipoMayorIgual0" name="ejercitos"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="tipoMayorIgual0">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== adalmauvil1-commits/Risk2x2Xml/doc/xml/mapa0.xml
<mapa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="mapa.xsd">
    <territorio>
        <nombre>Buztintxuri</nombre>
        <propietario>1</propietario>
        <ejercitos>4</ejercitos>
    </territorio>
    <territorio>
        <nombre>Arrosadia</nombre>
        <propietario>2</propietario>
        <ejercitos>3</ejercitos>
    </territorio>
    <territorio>
        <nombre>Txantrea</nombre>
        <propietario>1</propietario>
        <ejercitos>3</ejercitos>
    </territorio>
    <territorio>
        <nombre>Iturrama</nombre>
        <propietario>2</propietario>
        <ejercitos>4</ejercitos>
    </territorio>
</mapa>
